baseURL = 'https://adambcomer.com/'
languageCode = 'en-us'
title = 'Adam Comer'

disableKinds = ['taxonomy']

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[markup]
  [markup.highlight]
    noClasses = true
    style = 'catppuccin-mocha'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
